### ISSUE TITLE
Console error when trying to view shop next page

### ISSUE THREAD

**Issue by JAHMCR** [kiranhart/Shops#2]
**Describe Bug**
- When clicking on the "Next page" button from a shop, there is an error in the console

**How to Reproduce**
- Describe how to reproduce this bug: EX.
1. Create a shop with more than 1 page
2. Click on "Next page" button

**What should happen**
- It should change to the next page

**Console log**

[21:40:18] [Server thread/INFO]: 8[eShops8] Shops 3.4.0 encountered a ReflectionException! Please check your error.log and report this issue with the information in that file.
[21:40:18] [Server thread/INFO]: ca.tweetzy.shops.core.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.ReflectionUtil.getFieldContent(ReflectionUtil.java:199)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.ReflectionUtil.getFieldContent(ReflectionUtil.java:176)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.remain.Remain.updateInventoryTitle(Remain.java:1492)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.PlayerUtil.updateInventoryTitle(PlayerUtil.java:608)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.menu.MenuPagged.updatePage(MenuPagged.java:302)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.menu.MenuPagged.access$200(MenuPagged.java:32)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.menu.MenuPagged$2.onClickedInMenu(MenuPagged.java:278)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.menu.Menu.onButtonClick(Menu.java:978)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.menu.MenuPagged.onButtonClick(MenuPagged.java:444)
[21:40:18] [Server thread/INFO]: at Shops.jar//ca.tweetzy.shops.core.menu.MenuListener.onMenuClick(MenuListener.java:91)
[21:40:18] [Server thread/INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor549.execute(Unknown Source)
[21:40:18] [Server thread/INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[21:40:18] [Server thread/INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:40:18] [Server thread/INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:40:18] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[21:40:18] [Server thread/INFO]: at java.base/java.lang.Thread.run(Unknown Source)
[21:40:18] [Server thread/INFO]: 8[eShops8] 7!-----------------------------------------------------!
[21:40:18] [Server thread/INFO]: 8[eShops8]  cError clicking in menu MenuShopContentList{}
[21:40:18] [Server thread/INFO]: 8[eShops8] 7!-----------------------------------------------------!

**Server Information**
- Version 1.18.2
- Paper build 277
- Plugin version 3.4.0

**Comment by kiranhart** [comment]
update to 3.4.1

**Comment by JAHMCR** [comment]
Thanks! It works fine on 3.4.1
